# Beat map for intro v4 (ElevenLabs Xavier TTS of John's script). 57.0s.
NAVY=(30,42,69,255); RED=(255,71,87,255); GREEN=(46,213,115,255)
BEATS = [
    (1.90,  "V2","vid",  {"t0":0.0},             "I'M JOHN",                 GREEN),
    (5.20,  "V1","vid",  {"t0":0.0},             "A 2-YEAR EXPERIMENT",      RED),
    (8.17,  "K1","card", {},                     None,                       None),
    (13.15, "V2","vid",  {"t0":2.0},             "HOW WOMEN THINK",          NAVY),
    (14.63, "SMITTEN","still",{},                "WHAT TRIGGERS ATTRACTION", RED),
    (16.55, "V3","vid",  {"t0":0.0},             "SPOT RED FLAGS",           RED),
    (17.96, "CB1","card",{},                     None,                       None),
    (20.07, "S3","still",{},                     "WHAT TO SAY, HOW TO ACT",  NAVY),
    (22.10, "S4","still",{},                     "STAY OR WALK AWAY",        GREEN),
    (24.41, "S2","still",{},                     "EVERYTHING I LEARNED",     NAVY),
    (26.80, "CB2","card",{},                     None,                       None),
    (30.71, "V2","vid",  {"t0":4.5,"zoom":1.25}, "BETTER AT DATING",         GREEN),
    (33.66, "S1","still",{},                     "FOR THE BROS",             NAVY),
    (34.54, "S1","still",{"z0":1.3,"z1":1.45,"ytop":0.05}, "I GOT YOU.",     GREEN),
    (37.17, "SHOCKED","still",{},                "I SEARCHED YOUTUBE",       NAVY),
    (40.37, "SHOCKED","still",{"z0":1.3,"z1":1.45,"ytop":0.05}, "NO CHANNEL FOR THE BROS", RED),
    (44.00, "V2","vid",  {"t0":6.0},             "MY UNFILTERED TRUTH",      NAVY),
    (47.01, "S1","still",{},                     "KNOWLEDGE. SHARED.",       NAVY),
    (50.23, "S6","still",{},                     "THE BOOK IS COMING",       RED),
    (52.56, "V1","vid",  {"t0":5.5,"zoom":1.2},  "LIKE + SUBSCRIBE",         GREEN),
    (54.58, "V2","vid",  {"t0":1.0,"zoom":1.2},  "NEW VIDEOS COMING",        GREEN),
    (57.00, "CB3","card",{},                     None,                       None),
]
